# Generated by Django 4.2.17 on 2024-12-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('trader_id', models.CharField(max_length=50)),
                ('trade_type', models.CharField(choices=[('Lo', 'Limit Order'), ('Mo', 'Market Order')], max_length=2)),
                ('action_type', models.CharField(choices=[('New', 'New'), ('Mod', 'Modify'), ('Can', 'Cancel')], max_length=3)),
                ('bs_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
